FROM python:3.12.1-alpine

ENV PYTHONUNBUFFERED=1

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install psycopg2-binary

WORKDIR /app

COPY ./req.conf ./

RUN pip install -r req.conf

COPY . .
