# Generated by Django 4.2.10 on 2024-03-29 09:04

import catalogs.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=256, verbose_name='Сокращенное юр. наименование')),
                ('status', models.CharField(blank=True, choices=[('COM', 'Юридическое лицо'), ('PER', 'Физическое лицо'), ('OCOM', 'Юридическое лицо не резидент'), ('IND', 'Индивидуальный предприниматель')], default='COM', max_length=100, verbose_name='Юр/Физлицо')),
                ('inn', models.CharField(max_length=16, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=16, null=True, verbose_name='КПП')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Наименование полное')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='TypesOfProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид номенклатуры',
                'verbose_name_plural': 'Виды номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='ProductsGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Наименование')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='catalogs.productsgroup', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Группа номенклатуры',
                'verbose_name_plural': 'Группы номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=256, verbose_name='Наименование полное')),
                ('use_characteristic', models.CharField(choices=[('NU', 'Не используется'), ('GST', 'Общие для вида номенклатуры'), ('GOT', 'Общие с другим видом номенклатуры'), ('IND', 'Индивидуальные для номенклатуры')], default='NU', max_length=64, verbose_name='Варианты использования характеристик')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Описание')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogs.productsgroup', verbose_name='Группа')),
                ('type_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_product', to='catalogs.typesofproducts', verbose_name='Вид номенклатуры')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to=catalogs.models.image_dir_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='catalogs.products', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264, verbose_name='Наименование')),
                ('number', models.CharField(max_length=128, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('default', models.BooleanField(default=False, verbose_name='Использовать по умолчанию')),
                ('contractor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_contract', to='catalogs.contractors', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='organization_contract', to='catalogs.organizations', verbose_name='Организация')),
                ('partner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='partner_contract', to='catalogs.partners', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Договор с контрагентом',
                'verbose_name_plural': 'Договора с контрагентами',
            },
        ),
        migrations.AddField(
            model_name='contractors',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractor', to='catalogs.partners', verbose_name='Партнер'),
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_characteristics', to='catalogs.products', verbose_name='Номенклатура')),
                ('type_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_product_characteristics', to='catalogs.typesofproducts', verbose_name='Вид номенклатуры')),
            ],
            options={
                'verbose_name': 'Характеристика номенклатуры',
                'verbose_name_plural': 'Характеристики номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264, verbose_name='Наименование')),
                ('number', models.CharField(max_length=128, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('contractor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_agreement', to='catalogs.contractors', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_agreement', to='catalogs.organizations', verbose_name='Организация')),
                ('partner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_agreement', to='catalogs.partners', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Соглашение об условиях продаж',
                'verbose_name_plural': 'Соглашения об условиях продаж',
            },
        ),
    ]
