# Generated by Django 5.0 on 2024-02-13 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreements',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_agreement', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='contractor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_agreement', to='catalogs.contractors', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='contractor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_contract', to='catalogs.contractors', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='partner_contract', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='organization_contract', to='catalogs.organizations', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_agreement', to='catalogs.organizations', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='contractors',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractor', to='catalogs.partners', verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='catalogs.products', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_characteristics', to='catalogs.products', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='productsgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='catalogs.productsgroup', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='products',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogs.productsgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='products',
            name='type_of_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_product', to='catalogs.typesofproducts', verbose_name='Вид номенклатуры'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='type_of_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_product_characteristics', to='catalogs.typesofproducts', verbose_name='Вид номенклатуры'),
        ),
    ]
