# Generated by Django 5.0 on 2024-02-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='number',
            field=models.CharField(max_length=128, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='number',
            field=models.CharField(max_length=128, verbose_name='Номер'),
        ),
    ]
