# Generated by Django 5.0 on 2024-02-13 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_agreements_number_alter_contracts_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_agreement', to='catalogs.partners', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='partner_contract', to='catalogs.partners', verbose_name='Партнер'),
        ),
    ]
