# Generated by Django 4.2.10 on 2024-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_agreements_partner_alter_contracts_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Описание'),
        ),
    ]
