# Generated by Django 4.2.10 on 2024-03-30 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('number', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Номер')),
                ('site_status', models.CharField(choices=[('CR', 'Создан'), ('WR', 'В обработке'), ('PR', 'Обработан'), ('CL', 'Закрыт')], default='CR', max_length=10, verbose_name='Статус заказа на сайте')),
                ('agreement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_order', to='catalog.agreement', verbose_name='Соглашение')),
                ('contract', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_order', to='catalog.contract', verbose_name='Договор')),
                ('contractor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_order', to='catalog.contractor', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_order', to='catalog.organization', verbose_name='Организация')),
                ('partner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_order', to='catalog.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Заказ клиента',
                'verbose_name_plural': 'Заказы клиентов',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('characteristic', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_characteristic', to='catalog.characteristic', verbose_name='Характеристика')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_orders_detail', to='document.order', verbose_name='Заказ клиента')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='product_orders_detail', to='catalog.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Заказ клиента (Товары)',
                'verbose_name_plural': 'Заказы клиентов (Товары)',
            },
        ),
        migrations.CreateModel(
            name='ExchangeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время изменения')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_exchange_node', to='document.order', verbose_name='Заказ клиента')),
            ],
            options={
                'verbose_name': 'Измененный заказ',
                'verbose_name_plural': 'Измененные заказы',
            },
        ),
    ]

