# Generated by Django 4.2.10 on 2024-03-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_agreements_partner_alter_contracts_partner'),
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='characteristic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characteristics_prices', to='catalogs.characteristics', verbose_name='Характеристика'),
        ),
    ]
