# Generated by Django 5.0 on 2024-02-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_exchangenode_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangenode',
            name='updated_by',
        ),
    ]
