# Generated by Django 4.2.10 on 2024-03-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_agreements_partner_alter_contracts_partner'),
        ('documents', '0004_remove_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='site_status',
            field=models.CharField(choices=[('CR', 'Создан'), ('WR', 'Записан'), ('PR', 'Обработан'), ('CL', 'Закрыт')], default='CR', max_length=10, verbose_name='Статус заказа на сайте'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='contractor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_order', to='catalogs.contractors', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(default='', max_length=64, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_order', to='catalogs.organizations', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_order', to='catalogs.partners', verbose_name='Партнер'),
        ),
    ]
