# Generated by Django 4.2.10 on 2024-03-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_orders_site_status_alter_orders_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangenode',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_exchange_node', to='documents.orders', verbose_name='Заказ клиента'),
        ),
    ]
