# Generated by Django 4.2.10 on 2024-03-12 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_exchangenode_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetail',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_orders_detail', to='documents.orders', verbose_name='Заказ клиента'),
        ),
    ]
