# Generated by Django 4.2.10 on 2024-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_ordersdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='site_status',
            field=models.CharField(choices=[('CR', 'Создан'), ('WR', 'В обработке'), ('PR', 'Обработан'), ('CL', 'Закрыт')], default='CR', max_length=10, verbose_name='Статус заказа на сайте'),
        ),
    ]
